"""Initialisation table historique

Revision ID: 22d78cbcc35a
Revises: 
Create Date: 2026-01-27 22:34:31.082406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22d78cbcc35a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historique_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_prediction', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('revenu_mensuel', sa.Float(), nullable=True),
    sa.Column('distance_domicile_travail', sa.Integer(), nullable=True),
    sa.Column('satisfaction_environnement', sa.Integer(), nullable=True),
    sa.Column('heures_supp', sa.String(), nullable=True),
    sa.Column('annees_promo', sa.Integer(), nullable=True),
    sa.Column('satisfaction_equilibre', sa.Integer(), nullable=True),
    sa.Column('pee', sa.Integer(), nullable=True),
    sa.Column('poste_actuel', sa.Integer(), nullable=True),
    sa.Column('anciennete', sa.Integer(), nullable=True),
    sa.Column('exp_totale', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historique_predictions_id'), 'historique_predictions', ['id'], unique=False)
    op.drop_table('users')
    op.drop_table('employee')
    op.drop_table('prediction_logs')
    op.drop_table('auth_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('username_attempted', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_logs_pkey'))
    )
    op.create_table('prediction_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revenu_mensuel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance_domicile_travail', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('satisfaction_environnement', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heures_supplementaires', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('annees_promotion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_equilibre_pro_perso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_participation_pee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anciennete_poste_actuel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anciennete_entreprise', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_totale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prediction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('probabilite_depart', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('facteurs_risque', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('axes_amelioration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prediction_logs_pkey'))
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_employee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('revenu_mensuel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('statut_marital', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('departement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poste', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nombre_experiences_precedentes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annee_experience_totale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annees_dans_l_entreprise', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annees_dans_le_poste_actuel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_employee_environnement', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_evaluation_precedente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('niveau_hierarchique_poste', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_employee_nature_travail', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_employee_equipe', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_employee_equilibre_pro_perso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_evaluation_actuelle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heure_supplementaires', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('augementation_salaire_precedente', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('a_quitte_l_entreprise', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nombre_participation_pee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nb_formations_suivies', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_domicile_travail', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('niveau_education', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('domaine_etude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frequence_deplacement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('annees_depuis_la_derniere_promotion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annes_sous_responsable_actuel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_pkey')),
    sa.UniqueConstraint('id_employee', name=op.f('employee_id_employee_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_historique_predictions_id'), table_name='historique_predictions')
    op.drop_table('historique_predictions')
    # ### end Alembic commands ###
