"""Initialisation table historique

Revision ID: 22d78cbcc35a
Revises:
Create Date: 2026-01-27 22:34:31.082406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22d78cbcc35a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historique_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_prediction', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('revenu_mensuel', sa.Float(), nullable=True),
    sa.Column('distance_domicile_travail', sa.Integer(), nullable=True),
    sa.Column('satisfaction_environnement', sa.Integer(), nullable=True),
    sa.Column('heures_supp', sa.String(), nullable=True),
    sa.Column('annees_promo', sa.Integer(), nullable=True),
    sa.Column('satisfaction_equilibre', sa.Integer(), nullable=True),
    sa.Column('pee', sa.Integer(), nullable=True),
    sa.Column('poste_actuel', sa.Integer(), nullable=True),
    sa.Column('anciennete', sa.Integer(), nullable=True),
    sa.Column('exp_totale', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historique_predictions_id'), 'historique_predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historique_predictions_id'), table_name='historique_predictions')
    op.drop_table('historique_predictions')
    # ### end Alembic commands ###
